/**
 * Writes `www/config.js` so the bundled entry point and the Capacitor navigation allowlist
 * always agree on which origin the shell talks to. Run automatically by `bun run sync`.
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ORIGIN = process.env.TNR_ORIGIN ?? "https://www.theninja-rpg.com";

// Fail loudly rather than baking a bad origin into the binary: a malformed one breaks
// the shell, and a cleartext one would silently downgrade every request the app makes.
const origin = new URL(ORIGIN);
if (origin.protocol !== "https:") {
  throw new Error(`TNR_ORIGIN must be https, got ${origin.protocol}`);
}

const target = join(dirname(fileURLToPath(import.meta.url)), "..", "www", "config.js");
writeFileSync(
  target,
  `// Regenerated by \`bun run sync\` from TNR_ORIGIN. Committed so a fresh checkout builds\n` +
    `// against production without an extra step.\n` +
    `window.TNR_ORIGIN = ${JSON.stringify(ORIGIN)};\n`,
);
console.log(`mobile: entry point origin set to ${ORIGIN}`);
