/**
 * Writes `www/config.js` so the bundled entry point and the Capacitor navigation allowlist
 * always agree on which origin the shell talks to. Run automatically by `bun run sync`.
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ORIGIN = process.env.TNR_ORIGIN ?? "https://www.theninja-rpg.com";

// Fail loudly rather than baking a malformed origin into the binary.
new URL(ORIGIN);

const target = join(dirname(fileURLToPath(import.meta.url)), "..", "www", "config.js");
writeFileSync(
  target,
  `// Regenerated by \`bun run sync\` from TNR_ORIGIN. Committed so a fresh checkout builds\n` +
    `// against production without an extra step.\n` +
    `window.TNR_ORIGIN = ${JSON.stringify(ORIGIN)};\n`,
);
console.log(`mobile: entry point origin set to ${ORIGIN}`);
